In [ ]:
#https://www.kaggle.com/c/fake-news-pair-classification-challenge

In [2]:
# 讀CSV
import pandas as pd
train = pd.read_csv("train/train.csv", index_col=0)
train.head(3)

tid1  tid2                          title1_zh                  title2_zh   
id                                                                             
0      0     1      2017养老保险又新增两项，农村老人人人可申领，你领到了吗   警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京  \
3      2     3  "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小   
1      2     4  "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港       GDP首超香港？深圳澄清：还差一点点……   

                                            title1_en   
id                                                      
0   There are two new old-age insurance benefits f...  \
3   "If you do not come to Shenzhen, sooner or lat...   
1   "If you do not come to Shenzhen, sooner or lat...   

                                            title2_en      label  
id                                                                
0   Police disprove "bird's nest congress each per...  unrelated  
3   Shenzhen's GDP outstrips Hong Kong? Shenzhen S...  unrelated  
1   The GDP overtopped Hong Kong? Shenzhen clarifi...  unrelated

Number of columns: 3


In [3]:
cols = ['title1_zh', 
        'title2_zh', 
        'label']
train = train.loc[:, cols]
train.head(3)

title1_zh                  title2_zh      label
id                                                                         
0       2017养老保险又新增两项，农村老人人人可申领，你领到了吗   警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京  unrelated
3   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小  unrelated
1   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港       GDP首超香港？深圳澄清：还差一点点……  unrelated

In [11]:
num_rows = train.shape[0]
print("Number of rows:", num_rows)

Number of rows: 320552


In [4]:
text = 'I am Meng Lee, a data scientist based in Tokyo.'
words = text.split(' ')
words

['I', 'am', 'Meng', 'Lee,', 'a', 'data', 'scientist', 'based', 'in', 'Tokyo.']

In [106]:
import jieba.posseg as pseg

text = '我是李孟，在東京工作的數據科學家'
words = pseg.cut(text)
[word for word in words]

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\AU\AppData\Local\Temp\jieba.cache
Loading model cost 0.691 seconds.
Prefix dict has been built successfully.


[pair('我', 'r'),
 pair('是', 'v'),
 pair('李孟', 'nr'),
 pair('，', 'x'),
 pair('在', 'p'),
 pair('東京', 'ns'),
 pair('工作', 'vn'),
 pair('的', 'uj'),
 pair('數據', 'n'),
 pair('科學家', 'n')]

In [104]:
def jieba_tokenizer(text):
    words = pseg.cut(text)
    return ' '.join([
        word for word, flag in words if flag != 'x'])

In [ ]:
train['title1_tokenized'] = \
    train.loc[:, 'title1_zh'] \
         .apply(jieba_tokenizer)



In [27]:
train['title2_tokenized'] = \
    train.loc[:, 'title2_zh'] \
         .fillna('') \
         .apply(jieba_tokenizer)

In [35]:
train.iloc[:, 0:4].head()

title1_zh                   title2_zh      label   
id                                                                             
0       2017养老保险又新增两项，农村老人人人可申领，你领到了吗    警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京  unrelated  \
3   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港   深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小  unrelated   
1   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港        GDP首超香港？深圳澄清：还差一点点……  unrelated   
2   "你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  去年深圳GDP首超香港？深圳统计局辟谣：还差611亿  unrelated   
9                "用大蒜鉴别地沟油的方法,怎么鉴别地沟油     吃了30年食用油才知道，一片大蒜轻松鉴别地沟油     agreed   

                                   title1_tokenized  
id                                                   
0          2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗  
3   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
1   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
2   你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港  
9                        用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油

In [29]:
ecode = 'utf-8-sig'
train.to_csv("fake-news_jieba_10000.csv", encoding = ecode, index=False)

In [71]:
import pandas as pd
train = pd.read_csv("fake-news_jieba_10000.csv", index_col=0)

In [72]:
train.iloc[:, [0, 3]].head()

title2_zh   
title1_zh                                                       
 2017养老保险又新增两项，农村老人人人可申领，你领到了吗       警方辟谣“鸟巢大会每人领5万” 仍有老人坚持进京  \
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港   深圳GDP首超香港？深圳统计局辟谣：只是差距在缩小   
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港        GDP首超香港？深圳澄清：还差一点点……   
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  去年深圳GDP首超香港？深圳统计局辟谣：还差611亿   
"用大蒜鉴别地沟油的方法,怎么鉴别地沟油                  吃了30年食用油才知道，一片大蒜轻松鉴别地沟油   

                                                       title2_tokenized  
title1_zh                                                                
 2017养老保险又新增两项，农村老人人人可申领，你领到了吗        警方 辟谣 鸟巢 大会 每人 领 5 万 仍 有 老人 坚持 进京  
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港    深圳 GDP 首 超 香港 深圳 统计局 辟谣 只是 差距 在 缩小  
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港              GDP 首 超 香港 深圳 澄清 还 差 一点点  
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  去年 深圳 GDP 首 超 香港 深圳 统计局 辟谣 还 差 611 亿  
"用大蒜鉴别地沟油的方法,怎么鉴别地沟油                  吃 了 30 年 食用油 才 知道 一片 大蒜 轻松 鉴别 地沟油

In [73]:
num_rows = train.shape[0]
print("Number of rows:", num_rows)

Number of rows: 320552


In [74]:
import keras

from keras_preprocessing.text import Tokenizer
MAX_NUM_WORDS = 10000
tokenizer = Tokenizer(num_words=MAX_NUM_WORDS)

In [75]:
corpus_x1 = train.title1_tokenized
corpus_x2 = train.title2_tokenized
corpus = pd.concat([
    corpus_x1, corpus_x2])
corpus.shape

(641104,)

In [76]:
corpus_x1[1]

'你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港'

In [77]:
pd.DataFrame(corpus.iloc[:5],
             columns=['title'])

title
title1_zh                                                                         
 2017养老保险又新增两项，农村老人人人可申领，你领到了吗            2017 养老保险 又 新增 两项 农村 老人 人人 可 申领 你 领到 了 吗
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
"你不来深圳，早晚你儿子也要来"，不出10年深圳人均GDP将超香港  你 不 来 深圳 早晚 你 儿子 也 要 来 不出 10 年 深圳 人均 GDP 将 超 香港
"用大蒜鉴别地沟油的方法,怎么鉴别地沟油                                    用 大蒜 鉴别 地沟油 的 方法 怎么 鉴别 地沟油

In [78]:
#title1_tokenized 可能存在數字 使用map 把內容轉成字串
corpus_x1 = train.title1_tokenized.map(str)
corpus_x2 = train.title2_tokenized.map(str)
corpus = pd.concat([corpus_x1, corpus_x2])
tokenizer.fit_on_texts(corpus)

In [79]:
x1_train = tokenizer \
    .texts_to_sequences(corpus_x1)
x2_train = tokenizer \
    .texts_to_sequences(corpus_x2)

In [80]:
x1_train[0:5]


[[217, 1268, 32, 1178, 5967, 25, 489, 2877, 116, 5559, 4, 1850, 2, 13],
 [4,
  10,
  47,
  678,
  2558,
  4,
  166,
  34,
  17,
  47,
  5150,
  63,
  15,
  678,
  4502,
  3211,
  23,
  284,
  1181],
 [4,
  10,
  47,
  678,
  2558,
  4,
  166,
  34,
  17,
  47,
  5150,
  63,
  15,
  678,
  4502,
  3211,
  23,
  284,
  1181],
 [4,
  10,
  47,
  678,
  2558,
  4,
  166,
  34,
  17,
  47,
  5150,
  63,
  15,
  678,
  4502,
  3211,
  23,
  284,
  1181],
 [31, 320, 3372, 3062, 1, 95, 98, 3372, 3062]]

In [82]:
MAX_SEQUENCE_LENGTH = 20
from tensorflow.keras.preprocessing.sequence import pad_sequences


x1_train = pad_sequences(x1_train, maxlen=MAX_SEQUENCE_LENGTH)
x2_train = pad_sequences(x2_train, maxlen=MAX_SEQUENCE_LENGTH)


In [83]:
x1_train[0]

array([   0,    0,    0,    0,    0,    0,  217, 1268,   32, 1178, 5967,
         25,  489, 2877,  116, 5559,    4, 1850,    2,   13])

In [84]:
ecode = 'utf-8-sig'
x1_train_df=pd.DataFrame(x1_train)
x2_train_df=pd.DataFrame(x2_train)
x1_train_df = x1_train_df.iloc[:100]
x2_train_df = x2_train_df.iloc[:100]
x1_train_df.to_csv("fake-news_tokenized_sequences_x1_train.csv", encoding = ecode, index=False)
x2_train_df.to_csv("fake-news_tokenized_sequences_x2_train.csv", encoding = ecode, index=False)

In [85]:
import numpy as np 

# 定義每一個分類對應到的索引數字
label_to_index = {
    'unrelated': 0, 
    'agreed': 1, 
    'disagreed': 2
}

In [86]:
# 將分類標籤對應到剛定義的數字
y_train = train.label.apply(
    lambda x: label_to_index[x])

y_train = np.asarray(y_train) \
            .astype('float32')
y_train = keras \
    .utils \
    .to_categorical(y_train)
y_train[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [87]:
'''每 1 維度則對應到 1 個分類：

[1, 0, 0] 代表 label 為 unrelated
[0, 1, 0] 代表 label 為 agreed
[0, 0, 1] 代表 label 為 disagreed'''

'每 1 維度則對應到 1 個分類：\n\n[1, 0, 0] 代表 label 為 unrelated\n[0, 1, 0] 代表 label 為 agreed\n[0, 0, 1] 代表 label 為 disagreed'

In [88]:

x1_train.shape



(320552, 20)

In [89]:
y_train.shape

(320552, 3)

In [90]:
from sklearn.model_selection \
    import train_test_split

VALIDATION_RATIO = 0.1
# 小彩蛋
RANDOM_STATE = 9527

x1_train, x1_val, \
x2_train, x2_val, \
y_train, y_val = \
    train_test_split(
        x1_train, x2_train, y_train, 
        test_size=VALIDATION_RATIO, 
        random_state=RANDOM_STATE
)

In [91]:
print("Training Set")
print("-" * 10)
print(f"x1_train: {x1_train.shape}")
print(f"x2_train: {x2_train.shape}")
print(f"y_train : {y_train.shape}")

print("-" * 10)
print(f"x1_val:   {x1_val.shape}")
print(f"x2_val:   {x2_val.shape}")
print(f"y_val :   {y_val.shape}")
print("-" * 10)
print("Test Set")

Training Set
----------
x1_train: (288496, 20)
x2_train: (288496, 20)
y_train : (288496, 3)
----------
x1_val:   (32056, 20)
x2_val:   (32056, 20)
y_val :   (32056, 3)
----------
Test Set


In [92]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, Embedding, LSTM

In [93]:
# 基本參數設置，有幾個分類
NUM_CLASSES = 3

# 在語料庫裡有多少詞彙
MAX_NUM_WORDS = 10000

# 一個標題最長有幾個詞彙
MAX_SEQUENCE_LENGTH = 20

# 一個詞向量的維度
NUM_EMBEDDING_DIM = 256

# LSTM 輸出的向量維度
NUM_LSTM_UNITS = 128

In [94]:
# 建立孿生 LSTM 架構（Siamese LSTM）
from keras import Input
from keras.layers import Embedding, \
    LSTM, concatenate, Dense
from keras.models import Model

# 分別定義 2 個新聞標題 A & B 為模型輸入
# 兩個標題都是一個長度為 20 的數字序列
top_input = Input(shape=(MAX_SEQUENCE_LENGTH, ), dtype='int32')
bm_input = Input(shape=(MAX_SEQUENCE_LENGTH, ), dtype='int32')


# 詞嵌入層
# 經過詞嵌入層的轉換，兩個新聞標題都變成
# 一個詞向量的序列，而每個詞向量的維度
# 為 256
embedding_layer = Embedding(
    MAX_NUM_WORDS, NUM_EMBEDDING_DIM)
top_embedded = embedding_layer(top_input)
bm_embedded = embedding_layer(bm_input)


# LSTM 層
# 兩個新聞標題經過此層後
# 為一個 128 維度向量
shared_lstm = LSTM(NUM_LSTM_UNITS)
top_output = shared_lstm(top_embedded)
bm_output = shared_lstm(bm_embedded)

# 串接層將兩個新聞標題的結果串接單一向量
# 方便跟全連結層相連
merged = concatenate(
    [top_output, bm_output], 
    axis=-1)

# 全連接層搭配 Softmax Activation
# 可以回傳 3 個成對標題
# 屬於各類別的可能機率
dense = Dense(units=NUM_CLASSES, activation='softmax')
predictions = dense(merged)

# 我們的模型就是將數字序列的輸入，轉換
# 成 3 個分類的機率的所有步驟 / 層的總和
model = Model(inputs=[top_input, bm_input], outputs=predictions)

In [95]:
from keras.utils import plot_model
plot_model(
    model, 
    to_file='model.png', 
    show_shapes=True, 
    show_layer_names=False, 
    rankdir='LR')

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [96]:
model.summary()


Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_7 (InputLayer)           [(None, 20)]         0           []                               
                                                                                                  
 input_8 (InputLayer)           [(None, 20)]         0           []                               
                                                                                                  
 embedding_3 (Embedding)        (None, 20, 256)      2560000     ['input_7[0][0]',                
                                                                  'input_8[0][0]']                
                                                                                                  
 lstm_3 (LSTM)                  (None, 128)          197120      ['embedding_3[0][0]',      

In [97]:
#定義模型的損失函數
model.compile(
    #優化器
    optimizer='rmsprop',
    #損失函數
    loss='categorical_crossentropy',
    #評估指標
    metrics=['accuracy'])

In [98]:
x1_train[0]

array([   0,    0,    0,    0,    0, 4178, 2972,    9,   80,   87,  717,
         18,  474,    4,  968,    4,  823,   14, 1436,  721])

In [99]:
x2_train[0]

array([   0,    0,    0,    0,    0,    0,  411,  635, 1047,   90,   35,
        529,  408,  427,   22, 3015,  107,   68, 3330,  167])

In [100]:
y_train[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [101]:
# 決定一次要放多少成對標題給模型訓練
BATCH_SIZE = 512

# 決定模型要看整個訓練資料集幾遍
NUM_EPOCHS = 10

# 實際訓練模型
history = model.fit(
    # 輸入是兩個長度為 20 的數字序列
    x=[x1_train, x2_train], 
    y=y_train,
    batch_size=BATCH_SIZE,
    epochs=NUM_EPOCHS,
    # 每個 epoch 完後計算驗證資料集
    # 上的 Loss 以及準確度
    validation_data=(
        [x1_val, x2_val], 
        y_val
    ),
    # 每個 epoch 隨機調整訓練資料集
    # 裡頭的數據以讓訓練過程更穩定
    shuffle=True
)

Epoch 1/10
564/564 [==============================] - 194s 340ms/step - loss: 0.5403 - accuracy: 0.7411 - val_loss: 0.4512 - val_accuracy: 0.7878
Epoch 2/10
564/564 [==============================] - 185s 328ms/step - loss: 0.4272 - accuracy: 0.8012 - val_loss: 0.4192 - val_accuracy: 0.8061
Epoch 3/10
564/564 [==============================] - 194s 343ms/step - loss: 0.3927 - accuracy: 0.8211 - val_loss: 0.4166 - val_accuracy: 0.8103
Epoch 4/10
564/564 [==============================] - 190s 337ms/step - loss: 0.3701 - accuracy: 0.8336 - val_loss: 0.3913 - val_accuracy: 0.8216
Epoch 5/10
564/564 [==============================] - 186s 329ms/step - loss: 0.3529 - accuracy: 0.8423 - val_loss: 0.3883 - val_accuracy: 0.8247
Epoch 6/10
564/564 [==============================] - 183s 325ms/step - loss: 0.3372 - accuracy: 0.8509 - val_loss: 0.3917 - val_accuracy: 0.8258
Epoch 7/10
564/564 [==============================] - 183s 324ms/step - loss: 0.3227 - accuracy: 0.8590 - val_loss: 0.3934 -

In [102]:
import pandas as pd
test = pd.read_csv(
    "test/test.csv", index_col=0)
test.head(3)

tid1    tid2                        title1_zh   
id                                                        
321187  167562   59521  萨拉赫人气爆棚!埃及总统大选未参选获百万选票 现任总统压力山大  \
321190  167564   91315              萨达姆被捕后告诫美国的一句话，发人深思   
321189  167563  167564    萨达姆此项计划没有此国破坏的话，美国还会对伊拉克发动战争吗   

                          title2_zh   
id                                    
321187  辟谣！里昂官方否认费基尔加盟利物浦，难道是价格没谈拢？  \
321190    10大最让美国人相信的荒诞谣言，如蜥蜴人掌控着美国   
321189          萨达姆被捕后告诫美国的一句话，发人深思   

                                                title1_en   
id                                                          
321187  egypt 's presidential election failed to win m...  \
321190  A message from Saddam Hussein after he was cap...   
321189  Will the United States wage war on Iraq withou...   

                                                title2_en  
id                                                         
321187  Lyon! Lyon officials have denied that Felipe F...  
321190  The Top 10 Americans believe that the Lizard M...  
321189  A message from Saddam Hussein after he was cap...

In [109]:
# 以下步驟分別對新聞標題 A、B　進行
# 文本斷詞 / Word Segmentation


test['title1_tokenized'] = \
    test.loc[:, 'title1_zh'] \
        .apply(jieba_tokenizer)
test['title2_tokenized'] = \
    test.loc[:, 'title2_zh'] \
        .fillna('') \
        .apply(jieba_tokenizer)

In [110]:


# 將詞彙序列轉為索引數字的序列
#title1_tokenized 可能存在數字 使用map 把內容轉成字串
x1_test = train.title1_tokenized.map(str)
x2_test = train.title2_tokenized.map(str)


x1_test = tokenizer \
    .texts_to_sequences(
        test.title1_tokenized)
x2_test = tokenizer \
    .texts_to_sequences(
        test.title2_tokenized)

In [111]:
MAX_SEQUENCE_LENGTH = 20
from tensorflow.keras.preprocessing.sequence import pad_sequences


x1_test = pad_sequences(x1_test, maxlen=MAX_SEQUENCE_LENGTH)
x2_test = pad_sequences(x2_test, maxlen=MAX_SEQUENCE_LENGTH)


In [112]:
predictions = model.predict(
    [x1_test, x2_test])

2504/2504 [==============================] - 20s 8ms/step


In [ ]:
#跟我們之前討論過的一樣，模型針對每一筆成對新聞標題的輸入，會回傳給我們 3 個分類的機率值。

#現在，我們只要將機率值最大的類別當作答案，並將這個結果轉回對應的文本標籤即可上傳到 Kaggle

In [113]:
index_to_label = {v: k for k, v in label_to_index.items()}

test['Category'] = [index_to_label[idx] for idx in np.argmax(predictions, axis=1)]

submission = test \
    .loc[:, ['Category']] \
    .reset_index()

submission.columns = ['Id', 'Category']
submission.head()

Id   Category
0  321187  unrelated
1  321190  unrelated
2  321189  unrelated
3  321193  unrelated
4  321191  unrelated